---
- name: Install Nomad Client
  hosts: nomad_clients
  become: true
  vars:
    nomad_version: "1.6.1"  # Specify the desired version of Nomad
    nomad_binary_dir: "/usr/local/bin"  # Change this path if necessary
    cni_plugins_version: "v0.9.1"  # Specify the desired version of CNI plugins
    cni_plugins_dir: "/opt/cni/bin"  # Change this path if necessary
    nomad_server_address: 194.182.170.238
    nomad_client_machine_address: 194.182.168.73
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        - curl

    - name: Download Nomad binary
      get_url:
        url: "https://releases.hashicorp.com/nomad/{{ nomad_version }}/nomad_{{ nomad_version }}_linux_amd64.zip"
        dest: "{{ nomad_binary_dir }}/nomad_{{ nomad_version }}.zip"
        mode: "0644"  # Set appropriate permissions

    - name: Unzip Nomad binary
      unarchive:
        src: "{{ nomad_binary_dir }}/nomad_{{ nomad_version }}.zip"
        dest: "{{ nomad_binary_dir }}"
        remote_src: yes
        creates: "{{ nomad_binary_dir }}/nomad"  # This ensures it's not extracted again if the binary is already present

    - name: Ensure Nomad binary is executable
      file:
        path: "{{ nomad_binary_dir }}/nomad"
        mode: "+x"

    - name: Create Nomad configuration directory
      file:
        path: /etc/nomad.d
        state: directory
        mode: "0755"
        owner: root
        group: root

    - name: Create Nomad data directory
      file:
        path: /var/nomad
        state: directory
        mode: '0755'

    - name: Create Nomad client configuration file
      template:
        src: client.hcl.j2  # Ensure you have this template file in your ansible directory
        dest: /etc/nomad.d/client.hcl
      notify:
        - Restart Nomad

    - name: Create Nomad client service file
      template:
        src: client.service.j2  # Ensure you have this template file in your ansible directory
        dest: /etc/systemd/system/nomad-client.service
      notify: 
        - Restart systemd

    - name: Start Nomad client service
      systemd:
        name: nomad-client
        state: started
        enabled: yes

    - name: Create CNI plugins directory
      file:
        path: "{{ cni_plugins_dir }}"
        state: directory
        mode: '0755'

    - name: Download and install CNI plugins
      unarchive:
        src: "https://github.com/containernetworking/plugins/releases/download/{{ cni_plugins_version }}/cni-plugins-linux-amd64-{{ cni_plugins_version }}.tgz"
        dest: "{{ cni_plugins_dir }}"
        remote_src: true

  handlers:
    - name: Restart Nomad
      systemd:
        name: nomad-client
        state: restarted
        daemon_reload: yes

    - name: Reload systemd
      systemd:
        daemon_reload: yes