---
- name: Remove Nomad files
  hosts: nomad_servers
  become: true
  tasks:
    - name: Stop Nomad service
      systemd:
        name: nomad
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove Nomad binary
      file:
        path: /usr/local/bin/nomad
        state: absent

    - name: Remove Nomad configuration directory
      file:
        path: /etc/nomad.d
        state: absent

- name: Remove Nomad files
  hosts: nomad_clients
  become: true
  tasks:
    - name: Stop Nomad service
      systemd:
        name: nomad
        state: stopped
        enabled: no
      ignore_errors: yes

    - name: Remove Nomad binary
      file:
        path: /usr/local/bin/nomad
        state: absent

    - name: Remove Nomad configuration directory
      file:
        path: /etc/nomad.d
        state: absent