log:
  level: DEBUG

entryPoints:
  web:
    address: ":80"
  traefik:
    address: ":8080"

providers:
  nomad:
    endpoint:
      address: "http://127.0.0.1:4646"
    exposedByDefault: false

api:
  insecure: true
  dashboard: true